# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-09-16 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='options',
            field=models.CharField(blank=True, help_text='comma separated options', max_length=50, null=True),
        ),
    ]
